name: Godot CI/CD Pipeline

on:
  push:
    branches:
      - main
    
jobs:
  lint:
    name: Lint GDScript
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GDToolKit`
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install "gdtoolkit==4.*"

      - name: Lint scripts
        run: |
          cd "ashes-to-ash--a-poacher's-tale/scripts"
          gdlint . 

      - name: Lint tests
        run: |
          cd "ashes-to-ash--a-poacher's-tale/tests"
          gdlint .
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Godot Headless
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip Godot_v4.4.1-stable_linux.x86_64.zip -d godot_folder
          chmod +x godot_folder/Godot_v4.4.1-stable_linux.x86_64
          sudo mv godot_folder/Godot_v4.4.1-stable_linux.x86_64 /usr/local/bin/godot

      - name: Install GUT 
        run: |
          cd "ashes-to-ash--a-poacher's-tale/addons"
          wget https://github.com/bitwes/Gut/archive/ca6cf2006b887c5072410a3c89792110ba51d476.zip
          unzip ca6cf2006b887c5072410a3c89792110ba51d476.zip -d gut
          rm -rf ca6cf2006b887c5072410a3c89792110ba51d476.zip

      - name: Run GUT tests
        run: |
          cd "ashes-to-ash--a-poacher's-tale"
          godot --headless -d -s --path . addons/gut/gut_cmdln.gd -gdir=res://tests -ginclude_subdirs -gexit        

